permissionset 50000 GeneratedPermission
{
    Assignable = true;
    Permissions = tabledata "Data Debugger Analysis Buffer" = RIMD,
        tabledata "Data Debugger Change Buffer" = RIMD,
        tabledata "Data Debugger Live Stats" = RIMD,
        tabledata "Data Debugger Setup" = RIMD,
        tabledata "Data Debugger Table Filter" = RIMD,
        tabledata "DD Field Selection Buffer" = RIMD,
        tabledata "DD Table Pick Buffer" = RIMD,
        tabledata "DD Recording State" = RIMD,
        table "Data Debugger Analysis Buffer" = X,
        table "Data Debugger Change Buffer" = X,
        table "Data Debugger Live Stats" = X,
        table "Data Debugger Setup" = X,
        table "Data Debugger Table Filter" = X,
        table "DD Field Selection Buffer" = X,
        table "DD Table Pick Buffer" = X,
        table "DD Recording State" = X,
        codeunit "Data Debugger Analysis Engine" = X,
        codeunit "Data Debugger Context Manager" = X,
        codeunit "Data Debugger Event Handlers" = X,
        codeunit "Data Debugger Filter Manager" = X,
        codeunit "Data Debugger Session Manager" = X,
        page "Data Debugger" = X,
        page "Data Debugger Context Details" = X,
        page "Data Debugger Field Changes" = X,
        page "Data Debugger Live Stats" = X,
        page "Data Debugger Results" = X,
        page "Data Debugger Setup" = X,
        page "Data Debugger Table Filters" = X,
        page "Data Debugger Table Summary" = X,
        page "Data Debugger Transactions" = X,
        page "DD Advanced Analysis" = X,
        page "Event Recorder Custom" = X,
        page "DD Change Entry API" = X,
        page "DD Change Entry Preview" = X,
        page "DD Field Selection" = X,
        page "DD Table Pick" = X;
    //query "DD Recording Run API"=X;
}